//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LRequest.proto
namespace NetMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LRequest")]
  public partial class LRequest : global::ProtoBuf.IExtensible
  {
    public LRequest() {}
    
    private int _nEmployeeID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nEmployeeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nEmployeeID
    {
      get { return _nEmployeeID; }
      set { _nEmployeeID = value; }
    }
    private string _strSerialNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"strSerialNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strSerialNumber
    {
      get { return _strSerialNumber; }
      set { _strSerialNumber = value; }
    }
    private string _strUrl;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"strUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strUrl
    {
      get { return _strUrl; }
      set { _strUrl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}