// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LRequest.proto

package com.proto;

public final class Custom {
  private Custom() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 nEmployeeID = 1;
    /**
     * <code>required int32 nEmployeeID = 1;</code>
     */
    boolean hasNEmployeeID();
    /**
     * <code>required int32 nEmployeeID = 1;</code>
     */
    int getNEmployeeID();

    // required string strSerialNumber = 2;
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    boolean hasStrSerialNumber();
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    java.lang.String getStrSerialNumber();
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    com.google.protobuf.ByteString
        getStrSerialNumberBytes();

    // required string strUrl = 3;
    /**
     * <code>required string strUrl = 3;</code>
     */
    boolean hasStrUrl();
    /**
     * <code>required string strUrl = 3;</code>
     */
    java.lang.String getStrUrl();
    /**
     * <code>required string strUrl = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrUrlBytes();
  }
  /**
   * Protobuf type {@code LRequest}
   */
  public static final class LRequest extends
      com.google.protobuf.GeneratedMessage
      implements LRequestOrBuilder {
    // Use LRequest.newBuilder() to construct.
    private LRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LRequest defaultInstance;
    public static LRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nEmployeeID_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              strSerialNumber_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              strUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.Custom.internal_static_LRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.Custom.internal_static_LRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.Custom.LRequest.class, com.proto.Custom.LRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LRequest> PARSER =
        new com.google.protobuf.AbstractParser<LRequest>() {
      public LRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 nEmployeeID = 1;
    public static final int NEMPLOYEEID_FIELD_NUMBER = 1;
    private int nEmployeeID_;
    /**
     * <code>required int32 nEmployeeID = 1;</code>
     */
    public boolean hasNEmployeeID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 nEmployeeID = 1;</code>
     */
    public int getNEmployeeID() {
      return nEmployeeID_;
    }

    // required string strSerialNumber = 2;
    public static final int STRSERIALNUMBER_FIELD_NUMBER = 2;
    private java.lang.Object strSerialNumber_;
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    public boolean hasStrSerialNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    public java.lang.String getStrSerialNumber() {
      java.lang.Object ref = strSerialNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strSerialNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strSerialNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStrSerialNumberBytes() {
      java.lang.Object ref = strSerialNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strSerialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string strUrl = 3;
    public static final int STRURL_FIELD_NUMBER = 3;
    private java.lang.Object strUrl_;
    /**
     * <code>required string strUrl = 3;</code>
     */
    public boolean hasStrUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string strUrl = 3;</code>
     */
    public java.lang.String getStrUrl() {
      java.lang.Object ref = strUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrUrlBytes() {
      java.lang.Object ref = strUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      nEmployeeID_ = 0;
      strSerialNumber_ = "";
      strUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNEmployeeID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrSerialNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, nEmployeeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStrSerialNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getStrUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nEmployeeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStrSerialNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getStrUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.proto.Custom.LRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Custom.LRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Custom.LRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.Custom.LRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.Custom.LRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.proto.Custom.LRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.proto.Custom.LRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.proto.Custom.LRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.proto.Custom.LRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.proto.Custom.LRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.proto.Custom.LRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.proto.Custom.LRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.Custom.internal_static_LRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.Custom.internal_static_LRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.Custom.LRequest.class, com.proto.Custom.LRequest.Builder.class);
      }

      // Construct using com.proto.Custom.LRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nEmployeeID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        strSerialNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        strUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.Custom.internal_static_LRequest_descriptor;
      }

      public com.proto.Custom.LRequest getDefaultInstanceForType() {
        return com.proto.Custom.LRequest.getDefaultInstance();
      }

      public com.proto.Custom.LRequest build() {
        com.proto.Custom.LRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.proto.Custom.LRequest buildPartial() {
        com.proto.Custom.LRequest result = new com.proto.Custom.LRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nEmployeeID_ = nEmployeeID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.strSerialNumber_ = strSerialNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.strUrl_ = strUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.Custom.LRequest) {
          return mergeFrom((com.proto.Custom.LRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.Custom.LRequest other) {
        if (other == com.proto.Custom.LRequest.getDefaultInstance()) return this;
        if (other.hasNEmployeeID()) {
          setNEmployeeID(other.getNEmployeeID());
        }
        if (other.hasStrSerialNumber()) {
          bitField0_ |= 0x00000002;
          strSerialNumber_ = other.strSerialNumber_;
          onChanged();
        }
        if (other.hasStrUrl()) {
          bitField0_ |= 0x00000004;
          strUrl_ = other.strUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNEmployeeID()) {
          
          return false;
        }
        if (!hasStrSerialNumber()) {
          
          return false;
        }
        if (!hasStrUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.Custom.LRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.Custom.LRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 nEmployeeID = 1;
      private int nEmployeeID_ ;
      /**
       * <code>required int32 nEmployeeID = 1;</code>
       */
      public boolean hasNEmployeeID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 nEmployeeID = 1;</code>
       */
      public int getNEmployeeID() {
        return nEmployeeID_;
      }
      /**
       * <code>required int32 nEmployeeID = 1;</code>
       */
      public Builder setNEmployeeID(int value) {
        bitField0_ |= 0x00000001;
        nEmployeeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nEmployeeID = 1;</code>
       */
      public Builder clearNEmployeeID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nEmployeeID_ = 0;
        onChanged();
        return this;
      }

      // required string strSerialNumber = 2;
      private java.lang.Object strSerialNumber_ = "";
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public boolean hasStrSerialNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public java.lang.String getStrSerialNumber() {
        java.lang.Object ref = strSerialNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          strSerialNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStrSerialNumberBytes() {
        java.lang.Object ref = strSerialNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strSerialNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public Builder setStrSerialNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        strSerialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public Builder clearStrSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        strSerialNumber_ = getDefaultInstance().getStrSerialNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string strSerialNumber = 2;</code>
       */
      public Builder setStrSerialNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        strSerialNumber_ = value;
        onChanged();
        return this;
      }

      // required string strUrl = 3;
      private java.lang.Object strUrl_ = "";
      /**
       * <code>required string strUrl = 3;</code>
       */
      public boolean hasStrUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string strUrl = 3;</code>
       */
      public java.lang.String getStrUrl() {
        java.lang.Object ref = strUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          strUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strUrl = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrUrlBytes() {
        java.lang.Object ref = strUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strUrl = 3;</code>
       */
      public Builder setStrUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strUrl = 3;</code>
       */
      public Builder clearStrUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        strUrl_ = getDefaultInstance().getStrUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string strUrl = 3;</code>
       */
      public Builder setStrUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        strUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LRequest)
    }

    static {
      defaultInstance = new LRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LRequest.proto\"H\n\010LRequest\022\023\n\013nEmploye" +
      "eID\030\001 \002(\005\022\027\n\017strSerialNumber\030\002 \002(\t\022\016\n\006st" +
      "rUrl\030\003 \002(\tB\023\n\tcom.protoB\006Custom"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LRequest_descriptor,
              new java.lang.String[] { "NEmployeeID", "StrSerialNumber", "StrUrl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
