//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msgcharinfo")]
  public partial class msgcharinfo : global::ProtoBuf.IExtensible
  {
    public msgcharinfo() {}
    

    private uint _uaid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uaid
    {
      get { return _uaid; }
      set { _uaid = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private uint _kind = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kind
    {
      get { return _kind; }
      set { _kind = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _head = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private uint _phypower = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"phypower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint phypower
    {
      get { return _phypower; }
      set { _phypower = value; }
    }

    private uint _leadership = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"leadership", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint leadership
    {
      get { return _leadership; }
      set { _leadership = value; }
    }

    private uint _friendnum = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"friendnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendnum
    {
      get { return _friendnum; }
      set { _friendnum = value; }
    }

    private uint _gamecoin = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gamecoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gamecoin
    {
      get { return _gamecoin; }
      set { _gamecoin = value; }
    }

    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }

    private uint _friendshipoint = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"friendshipoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint friendshipoint
    {
      get { return _friendshipoint; }
      set { _friendshipoint = value; }
    }

    private uint _reservecur = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"reservecur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reservecur
    {
      get { return _reservecur; }
      set { _reservecur = value; }
    }

    private uint _nativepoint = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"nativepoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint nativepoint
    {
      get { return _nativepoint; }
      set { _nativepoint = value; }
    }

    private uint _summonupper = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"summonupper", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint summonupper
    {
      get { return _summonupper; }
      set { _summonupper = value; }
    }

    private uint _summonupperlimit = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"summonupperlimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint summonupperlimit
    {
      get { return _summonupperlimit; }
      set { _summonupperlimit = value; }
    }

    private string _createtime = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }

    private uint _guildid = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"guildid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint guildid
    {
      get { return _guildid; }
      set { _guildid = value; }
    }

    private uint _victory = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"victory", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint victory
    {
      get { return _victory; }
      set { _victory = value; }
    }

    private uint _fail = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"fail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fail
    {
      get { return _fail; }
      set { _fail = value; }
    }

    private uint _max_gamecoin = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"max_gamecoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_gamecoin
    {
      get { return _max_gamecoin; }
      set { _max_gamecoin = value; }
    }

    private uint _max_diamond = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"max_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_diamond
    {
      get { return _max_diamond; }
      set { _max_diamond = value; }
    }

    private uint _protectedtime = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"protectedtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint protectedtime
    {
      get { return _protectedtime; }
      set { _protectedtime = value; }
    }

    private uint _totalcost = default(uint);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"totalcost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint totalcost
    {
      get { return _totalcost; }
      set { _totalcost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"mymessage")]
  public partial class mymessage : global::ProtoBuf.IExtensible
  {
    public mymessage() {}
    

    private uint _myid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"myid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint myid
    {
      get { return _myid; }
      set { _myid = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}