// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package protobuf;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgcharinfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 uaid = 1;
    /**
     * <code>optional uint32 uaid = 1;</code>
     */
    boolean hasUaid();
    /**
     * <code>optional uint32 uaid = 1;</code>
     */
    int getUaid();

    // optional uint32 charid = 2;
    /**
     * <code>optional uint32 charid = 2;</code>
     */
    boolean hasCharid();
    /**
     * <code>optional uint32 charid = 2;</code>
     */
    int getCharid();

    // optional uint32 kind = 3;
    /**
     * <code>optional uint32 kind = 3;</code>
     */
    boolean hasKind();
    /**
     * <code>optional uint32 kind = 3;</code>
     */
    int getKind();

    // optional string name = 4;
    /**
     * <code>optional string name = 4;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string head = 5;
    /**
     * <code>optional string head = 5;</code>
     */
    boolean hasHead();
    /**
     * <code>optional string head = 5;</code>
     */
    java.lang.String getHead();
    /**
     * <code>optional string head = 5;</code>
     */
    com.google.protobuf.ByteString
        getHeadBytes();

    // optional uint32 level = 6;
    /**
     * <code>optional uint32 level = 6;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional uint32 level = 6;</code>
     */
    int getLevel();

    // optional uint32 exp = 7;
    /**
     * <code>optional uint32 exp = 7;</code>
     */
    boolean hasExp();
    /**
     * <code>optional uint32 exp = 7;</code>
     */
    int getExp();

    // optional uint32 phypower = 8;
    /**
     * <code>optional uint32 phypower = 8;</code>
     */
    boolean hasPhypower();
    /**
     * <code>optional uint32 phypower = 8;</code>
     */
    int getPhypower();

    // optional uint32 leadership = 9;
    /**
     * <code>optional uint32 leadership = 9;</code>
     */
    boolean hasLeadership();
    /**
     * <code>optional uint32 leadership = 9;</code>
     */
    int getLeadership();

    // optional uint32 friendnum = 10;
    /**
     * <code>optional uint32 friendnum = 10;</code>
     */
    boolean hasFriendnum();
    /**
     * <code>optional uint32 friendnum = 10;</code>
     */
    int getFriendnum();

    // optional uint32 gamecoin = 11;
    /**
     * <code>optional uint32 gamecoin = 11;</code>
     */
    boolean hasGamecoin();
    /**
     * <code>optional uint32 gamecoin = 11;</code>
     */
    int getGamecoin();

    // optional uint32 diamond = 12;
    /**
     * <code>optional uint32 diamond = 12;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional uint32 diamond = 12;</code>
     */
    int getDiamond();

    // optional uint32 friendshipoint = 13;
    /**
     * <code>optional uint32 friendshipoint = 13;</code>
     */
    boolean hasFriendshipoint();
    /**
     * <code>optional uint32 friendshipoint = 13;</code>
     */
    int getFriendshipoint();

    // optional uint32 reservecur = 14;
    /**
     * <code>optional uint32 reservecur = 14;</code>
     */
    boolean hasReservecur();
    /**
     * <code>optional uint32 reservecur = 14;</code>
     */
    int getReservecur();

    // optional uint32 nativepoint = 15;
    /**
     * <code>optional uint32 nativepoint = 15;</code>
     */
    boolean hasNativepoint();
    /**
     * <code>optional uint32 nativepoint = 15;</code>
     */
    int getNativepoint();

    // optional uint32 summonupper = 16;
    /**
     * <code>optional uint32 summonupper = 16;</code>
     */
    boolean hasSummonupper();
    /**
     * <code>optional uint32 summonupper = 16;</code>
     */
    int getSummonupper();

    // optional uint32 summonupperlimit = 17;
    /**
     * <code>optional uint32 summonupperlimit = 17;</code>
     */
    boolean hasSummonupperlimit();
    /**
     * <code>optional uint32 summonupperlimit = 17;</code>
     */
    int getSummonupperlimit();

    // optional string createtime = 18;
    /**
     * <code>optional string createtime = 18;</code>
     */
    boolean hasCreatetime();
    /**
     * <code>optional string createtime = 18;</code>
     */
    java.lang.String getCreatetime();
    /**
     * <code>optional string createtime = 18;</code>
     */
    com.google.protobuf.ByteString
        getCreatetimeBytes();

    // optional uint32 guildid = 19;
    /**
     * <code>optional uint32 guildid = 19;</code>
     */
    boolean hasGuildid();
    /**
     * <code>optional uint32 guildid = 19;</code>
     */
    int getGuildid();

    // optional uint32 victory = 20;
    /**
     * <code>optional uint32 victory = 20;</code>
     */
    boolean hasVictory();
    /**
     * <code>optional uint32 victory = 20;</code>
     */
    int getVictory();

    // optional uint32 fail = 21;
    /**
     * <code>optional uint32 fail = 21;</code>
     */
    boolean hasFail();
    /**
     * <code>optional uint32 fail = 21;</code>
     */
    int getFail();

    // optional uint32 max_gamecoin = 22;
    /**
     * <code>optional uint32 max_gamecoin = 22;</code>
     */
    boolean hasMaxGamecoin();
    /**
     * <code>optional uint32 max_gamecoin = 22;</code>
     */
    int getMaxGamecoin();

    // optional uint32 max_diamond = 23;
    /**
     * <code>optional uint32 max_diamond = 23;</code>
     */
    boolean hasMaxDiamond();
    /**
     * <code>optional uint32 max_diamond = 23;</code>
     */
    int getMaxDiamond();

    // optional uint32 protectedtime = 24;
    /**
     * <code>optional uint32 protectedtime = 24;</code>
     */
    boolean hasProtectedtime();
    /**
     * <code>optional uint32 protectedtime = 24;</code>
     */
    int getProtectedtime();

    // optional uint32 totalcost = 25;
    /**
     * <code>optional uint32 totalcost = 25;</code>
     */
    boolean hasTotalcost();
    /**
     * <code>optional uint32 totalcost = 25;</code>
     */
    int getTotalcost();
  }
  /**
   * Protobuf type {@code msgcharinfo}
   *
   * <pre>
   *角色信息结构
   * </pre>
   */
  public static final class msgcharinfo extends
      com.google.protobuf.GeneratedMessage
      implements msgcharinfoOrBuilder {
    // Use msgcharinfo.newBuilder() to construct.
    private msgcharinfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private msgcharinfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final msgcharinfo defaultInstance;
    public static msgcharinfo getDefaultInstance() {
      return defaultInstance;
    }

    public msgcharinfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private msgcharinfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uaid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              charid_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              kind_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              head_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              exp_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              phypower_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              leadership_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              friendnum_ = input.readUInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              gamecoin_ = input.readUInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              diamond_ = input.readUInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              friendshipoint_ = input.readUInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              reservecur_ = input.readUInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              nativepoint_ = input.readUInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              summonupper_ = input.readUInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              summonupperlimit_ = input.readUInt32();
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              createtime_ = input.readBytes();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              guildid_ = input.readUInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              victory_ = input.readUInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00100000;
              fail_ = input.readUInt32();
              break;
            }
            case 176: {
              bitField0_ |= 0x00200000;
              maxGamecoin_ = input.readUInt32();
              break;
            }
            case 184: {
              bitField0_ |= 0x00400000;
              maxDiamond_ = input.readUInt32();
              break;
            }
            case 192: {
              bitField0_ |= 0x00800000;
              protectedtime_ = input.readUInt32();
              break;
            }
            case 200: {
              bitField0_ |= 0x01000000;
              totalcost_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Common.internal_static_msgcharinfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Common.internal_static_msgcharinfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Common.msgcharinfo.class, protobuf.Common.msgcharinfo.Builder.class);
    }

    public static com.google.protobuf.Parser<msgcharinfo> PARSER =
        new com.google.protobuf.AbstractParser<msgcharinfo>() {
      public msgcharinfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msgcharinfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<msgcharinfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 uaid = 1;
    public static final int UAID_FIELD_NUMBER = 1;
    private int uaid_;
    /**
     * <code>optional uint32 uaid = 1;</code>
     */
    public boolean hasUaid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 uaid = 1;</code>
     */
    public int getUaid() {
      return uaid_;
    }

    // optional uint32 charid = 2;
    public static final int CHARID_FIELD_NUMBER = 2;
    private int charid_;
    /**
     * <code>optional uint32 charid = 2;</code>
     */
    public boolean hasCharid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 charid = 2;</code>
     */
    public int getCharid() {
      return charid_;
    }

    // optional uint32 kind = 3;
    public static final int KIND_FIELD_NUMBER = 3;
    private int kind_;
    /**
     * <code>optional uint32 kind = 3;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 kind = 3;</code>
     */
    public int getKind() {
      return kind_;
    }

    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string head = 5;
    public static final int HEAD_FIELD_NUMBER = 5;
    private java.lang.Object head_;
    /**
     * <code>optional string head = 5;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string head = 5;</code>
     */
    public java.lang.String getHead() {
      java.lang.Object ref = head_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          head_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHeadBytes() {
      java.lang.Object ref = head_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        head_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 level = 6;
    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <code>optional uint32 level = 6;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional uint32 exp = 7;
    public static final int EXP_FIELD_NUMBER = 7;
    private int exp_;
    /**
     * <code>optional uint32 exp = 7;</code>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 exp = 7;</code>
     */
    public int getExp() {
      return exp_;
    }

    // optional uint32 phypower = 8;
    public static final int PHYPOWER_FIELD_NUMBER = 8;
    private int phypower_;
    /**
     * <code>optional uint32 phypower = 8;</code>
     */
    public boolean hasPhypower() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 phypower = 8;</code>
     */
    public int getPhypower() {
      return phypower_;
    }

    // optional uint32 leadership = 9;
    public static final int LEADERSHIP_FIELD_NUMBER = 9;
    private int leadership_;
    /**
     * <code>optional uint32 leadership = 9;</code>
     */
    public boolean hasLeadership() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 leadership = 9;</code>
     */
    public int getLeadership() {
      return leadership_;
    }

    // optional uint32 friendnum = 10;
    public static final int FRIENDNUM_FIELD_NUMBER = 10;
    private int friendnum_;
    /**
     * <code>optional uint32 friendnum = 10;</code>
     */
    public boolean hasFriendnum() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 friendnum = 10;</code>
     */
    public int getFriendnum() {
      return friendnum_;
    }

    // optional uint32 gamecoin = 11;
    public static final int GAMECOIN_FIELD_NUMBER = 11;
    private int gamecoin_;
    /**
     * <code>optional uint32 gamecoin = 11;</code>
     */
    public boolean hasGamecoin() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint32 gamecoin = 11;</code>
     */
    public int getGamecoin() {
      return gamecoin_;
    }

    // optional uint32 diamond = 12;
    public static final int DIAMOND_FIELD_NUMBER = 12;
    private int diamond_;
    /**
     * <code>optional uint32 diamond = 12;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint32 diamond = 12;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    // optional uint32 friendshipoint = 13;
    public static final int FRIENDSHIPOINT_FIELD_NUMBER = 13;
    private int friendshipoint_;
    /**
     * <code>optional uint32 friendshipoint = 13;</code>
     */
    public boolean hasFriendshipoint() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint32 friendshipoint = 13;</code>
     */
    public int getFriendshipoint() {
      return friendshipoint_;
    }

    // optional uint32 reservecur = 14;
    public static final int RESERVECUR_FIELD_NUMBER = 14;
    private int reservecur_;
    /**
     * <code>optional uint32 reservecur = 14;</code>
     */
    public boolean hasReservecur() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional uint32 reservecur = 14;</code>
     */
    public int getReservecur() {
      return reservecur_;
    }

    // optional uint32 nativepoint = 15;
    public static final int NATIVEPOINT_FIELD_NUMBER = 15;
    private int nativepoint_;
    /**
     * <code>optional uint32 nativepoint = 15;</code>
     */
    public boolean hasNativepoint() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional uint32 nativepoint = 15;</code>
     */
    public int getNativepoint() {
      return nativepoint_;
    }

    // optional uint32 summonupper = 16;
    public static final int SUMMONUPPER_FIELD_NUMBER = 16;
    private int summonupper_;
    /**
     * <code>optional uint32 summonupper = 16;</code>
     */
    public boolean hasSummonupper() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional uint32 summonupper = 16;</code>
     */
    public int getSummonupper() {
      return summonupper_;
    }

    // optional uint32 summonupperlimit = 17;
    public static final int SUMMONUPPERLIMIT_FIELD_NUMBER = 17;
    private int summonupperlimit_;
    /**
     * <code>optional uint32 summonupperlimit = 17;</code>
     */
    public boolean hasSummonupperlimit() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional uint32 summonupperlimit = 17;</code>
     */
    public int getSummonupperlimit() {
      return summonupperlimit_;
    }

    // optional string createtime = 18;
    public static final int CREATETIME_FIELD_NUMBER = 18;
    private java.lang.Object createtime_;
    /**
     * <code>optional string createtime = 18;</code>
     */
    public boolean hasCreatetime() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>optional string createtime = 18;</code>
     */
    public java.lang.String getCreatetime() {
      java.lang.Object ref = createtime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createtime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string createtime = 18;</code>
     */
    public com.google.protobuf.ByteString
        getCreatetimeBytes() {
      java.lang.Object ref = createtime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 guildid = 19;
    public static final int GUILDID_FIELD_NUMBER = 19;
    private int guildid_;
    /**
     * <code>optional uint32 guildid = 19;</code>
     */
    public boolean hasGuildid() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>optional uint32 guildid = 19;</code>
     */
    public int getGuildid() {
      return guildid_;
    }

    // optional uint32 victory = 20;
    public static final int VICTORY_FIELD_NUMBER = 20;
    private int victory_;
    /**
     * <code>optional uint32 victory = 20;</code>
     */
    public boolean hasVictory() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>optional uint32 victory = 20;</code>
     */
    public int getVictory() {
      return victory_;
    }

    // optional uint32 fail = 21;
    public static final int FAIL_FIELD_NUMBER = 21;
    private int fail_;
    /**
     * <code>optional uint32 fail = 21;</code>
     */
    public boolean hasFail() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>optional uint32 fail = 21;</code>
     */
    public int getFail() {
      return fail_;
    }

    // optional uint32 max_gamecoin = 22;
    public static final int MAX_GAMECOIN_FIELD_NUMBER = 22;
    private int maxGamecoin_;
    /**
     * <code>optional uint32 max_gamecoin = 22;</code>
     */
    public boolean hasMaxGamecoin() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>optional uint32 max_gamecoin = 22;</code>
     */
    public int getMaxGamecoin() {
      return maxGamecoin_;
    }

    // optional uint32 max_diamond = 23;
    public static final int MAX_DIAMOND_FIELD_NUMBER = 23;
    private int maxDiamond_;
    /**
     * <code>optional uint32 max_diamond = 23;</code>
     */
    public boolean hasMaxDiamond() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    /**
     * <code>optional uint32 max_diamond = 23;</code>
     */
    public int getMaxDiamond() {
      return maxDiamond_;
    }

    // optional uint32 protectedtime = 24;
    public static final int PROTECTEDTIME_FIELD_NUMBER = 24;
    private int protectedtime_;
    /**
     * <code>optional uint32 protectedtime = 24;</code>
     */
    public boolean hasProtectedtime() {
      return ((bitField0_ & 0x00800000) == 0x00800000);
    }
    /**
     * <code>optional uint32 protectedtime = 24;</code>
     */
    public int getProtectedtime() {
      return protectedtime_;
    }

    // optional uint32 totalcost = 25;
    public static final int TOTALCOST_FIELD_NUMBER = 25;
    private int totalcost_;
    /**
     * <code>optional uint32 totalcost = 25;</code>
     */
    public boolean hasTotalcost() {
      return ((bitField0_ & 0x01000000) == 0x01000000);
    }
    /**
     * <code>optional uint32 totalcost = 25;</code>
     */
    public int getTotalcost() {
      return totalcost_;
    }

    private void initFields() {
      uaid_ = 0;
      charid_ = 0;
      kind_ = 0;
      name_ = "";
      head_ = "";
      level_ = 0;
      exp_ = 0;
      phypower_ = 0;
      leadership_ = 0;
      friendnum_ = 0;
      gamecoin_ = 0;
      diamond_ = 0;
      friendshipoint_ = 0;
      reservecur_ = 0;
      nativepoint_ = 0;
      summonupper_ = 0;
      summonupperlimit_ = 0;
      createtime_ = "";
      guildid_ = 0;
      victory_ = 0;
      fail_ = 0;
      maxGamecoin_ = 0;
      maxDiamond_ = 0;
      protectedtime_ = 0;
      totalcost_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, uaid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, charid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, kind_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getHeadBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, exp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, phypower_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, leadership_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, friendnum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, gamecoin_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(12, diamond_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(13, friendshipoint_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeUInt32(14, reservecur_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt32(15, nativepoint_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeUInt32(16, summonupper_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeUInt32(17, summonupperlimit_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getCreatetimeBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeUInt32(19, guildid_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeUInt32(20, victory_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeUInt32(21, fail_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeUInt32(22, maxGamecoin_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeUInt32(23, maxDiamond_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        output.writeUInt32(24, protectedtime_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        output.writeUInt32(25, totalcost_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uaid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, charid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, kind_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getHeadBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, exp_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, phypower_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, leadership_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, friendnum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, gamecoin_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, diamond_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, friendshipoint_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, reservecur_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, nativepoint_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(16, summonupper_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(17, summonupperlimit_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getCreatetimeBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(19, guildid_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(20, victory_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(21, fail_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(22, maxGamecoin_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(23, maxDiamond_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(24, protectedtime_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(25, totalcost_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.Common.msgcharinfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Common.msgcharinfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Common.msgcharinfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Common.msgcharinfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Common.msgcharinfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Common.msgcharinfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.Common.msgcharinfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.Common.msgcharinfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.Common.msgcharinfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Common.msgcharinfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.Common.msgcharinfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msgcharinfo}
     *
     * <pre>
     *角色信息结构
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.Common.msgcharinfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Common.internal_static_msgcharinfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Common.internal_static_msgcharinfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.Common.msgcharinfo.class, protobuf.Common.msgcharinfo.Builder.class);
      }

      // Construct using protobuf.Common.msgcharinfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uaid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        charid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        kind_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        head_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        phypower_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        leadership_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        friendnum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        gamecoin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        friendshipoint_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        reservecur_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        nativepoint_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        summonupper_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        summonupperlimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        createtime_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        guildid_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        victory_ = 0;
        bitField0_ = (bitField0_ & ~0x00080000);
        fail_ = 0;
        bitField0_ = (bitField0_ & ~0x00100000);
        maxGamecoin_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        maxDiamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00400000);
        protectedtime_ = 0;
        bitField0_ = (bitField0_ & ~0x00800000);
        totalcost_ = 0;
        bitField0_ = (bitField0_ & ~0x01000000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Common.internal_static_msgcharinfo_descriptor;
      }

      public protobuf.Common.msgcharinfo getDefaultInstanceForType() {
        return protobuf.Common.msgcharinfo.getDefaultInstance();
      }

      public protobuf.Common.msgcharinfo build() {
        protobuf.Common.msgcharinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.Common.msgcharinfo buildPartial() {
        protobuf.Common.msgcharinfo result = new protobuf.Common.msgcharinfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uaid_ = uaid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.charid_ = charid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.head_ = head_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.phypower_ = phypower_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.leadership_ = leadership_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.friendnum_ = friendnum_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.gamecoin_ = gamecoin_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.diamond_ = diamond_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.friendshipoint_ = friendshipoint_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.reservecur_ = reservecur_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.nativepoint_ = nativepoint_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.summonupper_ = summonupper_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.summonupperlimit_ = summonupperlimit_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.createtime_ = createtime_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.guildid_ = guildid_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.victory_ = victory_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.fail_ = fail_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.maxGamecoin_ = maxGamecoin_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.maxDiamond_ = maxDiamond_;
        if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
          to_bitField0_ |= 0x00800000;
        }
        result.protectedtime_ = protectedtime_;
        if (((from_bitField0_ & 0x01000000) == 0x01000000)) {
          to_bitField0_ |= 0x01000000;
        }
        result.totalcost_ = totalcost_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Common.msgcharinfo) {
          return mergeFrom((protobuf.Common.msgcharinfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.Common.msgcharinfo other) {
        if (other == protobuf.Common.msgcharinfo.getDefaultInstance()) return this;
        if (other.hasUaid()) {
          setUaid(other.getUaid());
        }
        if (other.hasCharid()) {
          setCharid(other.getCharid());
        }
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasHead()) {
          bitField0_ |= 0x00000010;
          head_ = other.head_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasPhypower()) {
          setPhypower(other.getPhypower());
        }
        if (other.hasLeadership()) {
          setLeadership(other.getLeadership());
        }
        if (other.hasFriendnum()) {
          setFriendnum(other.getFriendnum());
        }
        if (other.hasGamecoin()) {
          setGamecoin(other.getGamecoin());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        if (other.hasFriendshipoint()) {
          setFriendshipoint(other.getFriendshipoint());
        }
        if (other.hasReservecur()) {
          setReservecur(other.getReservecur());
        }
        if (other.hasNativepoint()) {
          setNativepoint(other.getNativepoint());
        }
        if (other.hasSummonupper()) {
          setSummonupper(other.getSummonupper());
        }
        if (other.hasSummonupperlimit()) {
          setSummonupperlimit(other.getSummonupperlimit());
        }
        if (other.hasCreatetime()) {
          bitField0_ |= 0x00020000;
          createtime_ = other.createtime_;
          onChanged();
        }
        if (other.hasGuildid()) {
          setGuildid(other.getGuildid());
        }
        if (other.hasVictory()) {
          setVictory(other.getVictory());
        }
        if (other.hasFail()) {
          setFail(other.getFail());
        }
        if (other.hasMaxGamecoin()) {
          setMaxGamecoin(other.getMaxGamecoin());
        }
        if (other.hasMaxDiamond()) {
          setMaxDiamond(other.getMaxDiamond());
        }
        if (other.hasProtectedtime()) {
          setProtectedtime(other.getProtectedtime());
        }
        if (other.hasTotalcost()) {
          setTotalcost(other.getTotalcost());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.Common.msgcharinfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.Common.msgcharinfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 uaid = 1;
      private int uaid_ ;
      /**
       * <code>optional uint32 uaid = 1;</code>
       */
      public boolean hasUaid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 uaid = 1;</code>
       */
      public int getUaid() {
        return uaid_;
      }
      /**
       * <code>optional uint32 uaid = 1;</code>
       */
      public Builder setUaid(int value) {
        bitField0_ |= 0x00000001;
        uaid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uaid = 1;</code>
       */
      public Builder clearUaid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uaid_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 charid = 2;
      private int charid_ ;
      /**
       * <code>optional uint32 charid = 2;</code>
       */
      public boolean hasCharid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 charid = 2;</code>
       */
      public int getCharid() {
        return charid_;
      }
      /**
       * <code>optional uint32 charid = 2;</code>
       */
      public Builder setCharid(int value) {
        bitField0_ |= 0x00000002;
        charid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 charid = 2;</code>
       */
      public Builder clearCharid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        charid_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 kind = 3;
      private int kind_ ;
      /**
       * <code>optional uint32 kind = 3;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 kind = 3;</code>
       */
      public int getKind() {
        return kind_;
      }
      /**
       * <code>optional uint32 kind = 3;</code>
       */
      public Builder setKind(int value) {
        bitField0_ |= 0x00000004;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 kind = 3;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kind_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 4;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string head = 5;
      private java.lang.Object head_ = "";
      /**
       * <code>optional string head = 5;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string head = 5;</code>
       */
      public java.lang.String getHead() {
        java.lang.Object ref = head_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          head_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHeadBytes() {
        java.lang.Object ref = head_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          head_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head = 5;</code>
       */
      public Builder setHead(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head = 5;</code>
       */
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000010);
        head_ = getDefaultInstance().getHead();
        onChanged();
        return this;
      }
      /**
       * <code>optional string head = 5;</code>
       */
      public Builder setHeadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        head_ = value;
        onChanged();
        return this;
      }

      // optional uint32 level = 6;
      private int level_ ;
      /**
       * <code>optional uint32 level = 6;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional uint32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 level = 6;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 exp = 7;
      private int exp_ ;
      /**
       * <code>optional uint32 exp = 7;</code>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 exp = 7;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional uint32 exp = 7;</code>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000040;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 exp = 7;</code>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        exp_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 phypower = 8;
      private int phypower_ ;
      /**
       * <code>optional uint32 phypower = 8;</code>
       */
      public boolean hasPhypower() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 phypower = 8;</code>
       */
      public int getPhypower() {
        return phypower_;
      }
      /**
       * <code>optional uint32 phypower = 8;</code>
       */
      public Builder setPhypower(int value) {
        bitField0_ |= 0x00000080;
        phypower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 phypower = 8;</code>
       */
      public Builder clearPhypower() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phypower_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 leadership = 9;
      private int leadership_ ;
      /**
       * <code>optional uint32 leadership = 9;</code>
       */
      public boolean hasLeadership() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 leadership = 9;</code>
       */
      public int getLeadership() {
        return leadership_;
      }
      /**
       * <code>optional uint32 leadership = 9;</code>
       */
      public Builder setLeadership(int value) {
        bitField0_ |= 0x00000100;
        leadership_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 leadership = 9;</code>
       */
      public Builder clearLeadership() {
        bitField0_ = (bitField0_ & ~0x00000100);
        leadership_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 friendnum = 10;
      private int friendnum_ ;
      /**
       * <code>optional uint32 friendnum = 10;</code>
       */
      public boolean hasFriendnum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 friendnum = 10;</code>
       */
      public int getFriendnum() {
        return friendnum_;
      }
      /**
       * <code>optional uint32 friendnum = 10;</code>
       */
      public Builder setFriendnum(int value) {
        bitField0_ |= 0x00000200;
        friendnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 friendnum = 10;</code>
       */
      public Builder clearFriendnum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        friendnum_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 gamecoin = 11;
      private int gamecoin_ ;
      /**
       * <code>optional uint32 gamecoin = 11;</code>
       */
      public boolean hasGamecoin() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint32 gamecoin = 11;</code>
       */
      public int getGamecoin() {
        return gamecoin_;
      }
      /**
       * <code>optional uint32 gamecoin = 11;</code>
       */
      public Builder setGamecoin(int value) {
        bitField0_ |= 0x00000400;
        gamecoin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 gamecoin = 11;</code>
       */
      public Builder clearGamecoin() {
        bitField0_ = (bitField0_ & ~0x00000400);
        gamecoin_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 diamond = 12;
      private int diamond_ ;
      /**
       * <code>optional uint32 diamond = 12;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint32 diamond = 12;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional uint32 diamond = 12;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000800;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 diamond = 12;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000800);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 friendshipoint = 13;
      private int friendshipoint_ ;
      /**
       * <code>optional uint32 friendshipoint = 13;</code>
       */
      public boolean hasFriendshipoint() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint32 friendshipoint = 13;</code>
       */
      public int getFriendshipoint() {
        return friendshipoint_;
      }
      /**
       * <code>optional uint32 friendshipoint = 13;</code>
       */
      public Builder setFriendshipoint(int value) {
        bitField0_ |= 0x00001000;
        friendshipoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 friendshipoint = 13;</code>
       */
      public Builder clearFriendshipoint() {
        bitField0_ = (bitField0_ & ~0x00001000);
        friendshipoint_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 reservecur = 14;
      private int reservecur_ ;
      /**
       * <code>optional uint32 reservecur = 14;</code>
       */
      public boolean hasReservecur() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional uint32 reservecur = 14;</code>
       */
      public int getReservecur() {
        return reservecur_;
      }
      /**
       * <code>optional uint32 reservecur = 14;</code>
       */
      public Builder setReservecur(int value) {
        bitField0_ |= 0x00002000;
        reservecur_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 reservecur = 14;</code>
       */
      public Builder clearReservecur() {
        bitField0_ = (bitField0_ & ~0x00002000);
        reservecur_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 nativepoint = 15;
      private int nativepoint_ ;
      /**
       * <code>optional uint32 nativepoint = 15;</code>
       */
      public boolean hasNativepoint() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional uint32 nativepoint = 15;</code>
       */
      public int getNativepoint() {
        return nativepoint_;
      }
      /**
       * <code>optional uint32 nativepoint = 15;</code>
       */
      public Builder setNativepoint(int value) {
        bitField0_ |= 0x00004000;
        nativepoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 nativepoint = 15;</code>
       */
      public Builder clearNativepoint() {
        bitField0_ = (bitField0_ & ~0x00004000);
        nativepoint_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 summonupper = 16;
      private int summonupper_ ;
      /**
       * <code>optional uint32 summonupper = 16;</code>
       */
      public boolean hasSummonupper() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional uint32 summonupper = 16;</code>
       */
      public int getSummonupper() {
        return summonupper_;
      }
      /**
       * <code>optional uint32 summonupper = 16;</code>
       */
      public Builder setSummonupper(int value) {
        bitField0_ |= 0x00008000;
        summonupper_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 summonupper = 16;</code>
       */
      public Builder clearSummonupper() {
        bitField0_ = (bitField0_ & ~0x00008000);
        summonupper_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 summonupperlimit = 17;
      private int summonupperlimit_ ;
      /**
       * <code>optional uint32 summonupperlimit = 17;</code>
       */
      public boolean hasSummonupperlimit() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional uint32 summonupperlimit = 17;</code>
       */
      public int getSummonupperlimit() {
        return summonupperlimit_;
      }
      /**
       * <code>optional uint32 summonupperlimit = 17;</code>
       */
      public Builder setSummonupperlimit(int value) {
        bitField0_ |= 0x00010000;
        summonupperlimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 summonupperlimit = 17;</code>
       */
      public Builder clearSummonupperlimit() {
        bitField0_ = (bitField0_ & ~0x00010000);
        summonupperlimit_ = 0;
        onChanged();
        return this;
      }

      // optional string createtime = 18;
      private java.lang.Object createtime_ = "";
      /**
       * <code>optional string createtime = 18;</code>
       */
      public boolean hasCreatetime() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>optional string createtime = 18;</code>
       */
      public java.lang.String getCreatetime() {
        java.lang.Object ref = createtime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          createtime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string createtime = 18;</code>
       */
      public com.google.protobuf.ByteString
          getCreatetimeBytes() {
        java.lang.Object ref = createtime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createtime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string createtime = 18;</code>
       */
      public Builder setCreatetime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        createtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string createtime = 18;</code>
       */
      public Builder clearCreatetime() {
        bitField0_ = (bitField0_ & ~0x00020000);
        createtime_ = getDefaultInstance().getCreatetime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string createtime = 18;</code>
       */
      public Builder setCreatetimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        createtime_ = value;
        onChanged();
        return this;
      }

      // optional uint32 guildid = 19;
      private int guildid_ ;
      /**
       * <code>optional uint32 guildid = 19;</code>
       */
      public boolean hasGuildid() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>optional uint32 guildid = 19;</code>
       */
      public int getGuildid() {
        return guildid_;
      }
      /**
       * <code>optional uint32 guildid = 19;</code>
       */
      public Builder setGuildid(int value) {
        bitField0_ |= 0x00040000;
        guildid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 guildid = 19;</code>
       */
      public Builder clearGuildid() {
        bitField0_ = (bitField0_ & ~0x00040000);
        guildid_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 victory = 20;
      private int victory_ ;
      /**
       * <code>optional uint32 victory = 20;</code>
       */
      public boolean hasVictory() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>optional uint32 victory = 20;</code>
       */
      public int getVictory() {
        return victory_;
      }
      /**
       * <code>optional uint32 victory = 20;</code>
       */
      public Builder setVictory(int value) {
        bitField0_ |= 0x00080000;
        victory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 victory = 20;</code>
       */
      public Builder clearVictory() {
        bitField0_ = (bitField0_ & ~0x00080000);
        victory_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 fail = 21;
      private int fail_ ;
      /**
       * <code>optional uint32 fail = 21;</code>
       */
      public boolean hasFail() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>optional uint32 fail = 21;</code>
       */
      public int getFail() {
        return fail_;
      }
      /**
       * <code>optional uint32 fail = 21;</code>
       */
      public Builder setFail(int value) {
        bitField0_ |= 0x00100000;
        fail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 fail = 21;</code>
       */
      public Builder clearFail() {
        bitField0_ = (bitField0_ & ~0x00100000);
        fail_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 max_gamecoin = 22;
      private int maxGamecoin_ ;
      /**
       * <code>optional uint32 max_gamecoin = 22;</code>
       */
      public boolean hasMaxGamecoin() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>optional uint32 max_gamecoin = 22;</code>
       */
      public int getMaxGamecoin() {
        return maxGamecoin_;
      }
      /**
       * <code>optional uint32 max_gamecoin = 22;</code>
       */
      public Builder setMaxGamecoin(int value) {
        bitField0_ |= 0x00200000;
        maxGamecoin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 max_gamecoin = 22;</code>
       */
      public Builder clearMaxGamecoin() {
        bitField0_ = (bitField0_ & ~0x00200000);
        maxGamecoin_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 max_diamond = 23;
      private int maxDiamond_ ;
      /**
       * <code>optional uint32 max_diamond = 23;</code>
       */
      public boolean hasMaxDiamond() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      /**
       * <code>optional uint32 max_diamond = 23;</code>
       */
      public int getMaxDiamond() {
        return maxDiamond_;
      }
      /**
       * <code>optional uint32 max_diamond = 23;</code>
       */
      public Builder setMaxDiamond(int value) {
        bitField0_ |= 0x00400000;
        maxDiamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 max_diamond = 23;</code>
       */
      public Builder clearMaxDiamond() {
        bitField0_ = (bitField0_ & ~0x00400000);
        maxDiamond_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 protectedtime = 24;
      private int protectedtime_ ;
      /**
       * <code>optional uint32 protectedtime = 24;</code>
       */
      public boolean hasProtectedtime() {
        return ((bitField0_ & 0x00800000) == 0x00800000);
      }
      /**
       * <code>optional uint32 protectedtime = 24;</code>
       */
      public int getProtectedtime() {
        return protectedtime_;
      }
      /**
       * <code>optional uint32 protectedtime = 24;</code>
       */
      public Builder setProtectedtime(int value) {
        bitField0_ |= 0x00800000;
        protectedtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 protectedtime = 24;</code>
       */
      public Builder clearProtectedtime() {
        bitField0_ = (bitField0_ & ~0x00800000);
        protectedtime_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 totalcost = 25;
      private int totalcost_ ;
      /**
       * <code>optional uint32 totalcost = 25;</code>
       */
      public boolean hasTotalcost() {
        return ((bitField0_ & 0x01000000) == 0x01000000);
      }
      /**
       * <code>optional uint32 totalcost = 25;</code>
       */
      public int getTotalcost() {
        return totalcost_;
      }
      /**
       * <code>optional uint32 totalcost = 25;</code>
       */
      public Builder setTotalcost(int value) {
        bitField0_ |= 0x01000000;
        totalcost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 totalcost = 25;</code>
       */
      public Builder clearTotalcost() {
        bitField0_ = (bitField0_ & ~0x01000000);
        totalcost_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msgcharinfo)
    }

    static {
      defaultInstance = new msgcharinfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msgcharinfo)
  }

  public interface mymessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 myid = 1;
    /**
     * <code>optional uint32 myid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    boolean hasMyid();
    /**
     * <code>optional uint32 myid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    int getMyid();

    // optional string message = 2;
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code mymessage}
   */
  public static final class mymessage extends
      com.google.protobuf.GeneratedMessage
      implements mymessageOrBuilder {
    // Use mymessage.newBuilder() to construct.
    private mymessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private mymessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final mymessage defaultInstance;
    public static mymessage getDefaultInstance() {
      return defaultInstance;
    }

    public mymessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private mymessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              myid_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Common.internal_static_mymessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Common.internal_static_mymessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.Common.mymessage.class, protobuf.Common.mymessage.Builder.class);
    }

    public static com.google.protobuf.Parser<mymessage> PARSER =
        new com.google.protobuf.AbstractParser<mymessage>() {
      public mymessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new mymessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<mymessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 myid = 1;
    public static final int MYID_FIELD_NUMBER = 1;
    private int myid_;
    /**
     * <code>optional uint32 myid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    public boolean hasMyid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 myid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    public int getMyid() {
      return myid_;
    }

    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     *
     * <pre>
     *发送的信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      myid_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, myid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, myid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.Common.mymessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Common.mymessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Common.mymessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.Common.mymessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.Common.mymessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Common.mymessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.Common.mymessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.Common.mymessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.Common.mymessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.Common.mymessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.Common.mymessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.Common.mymessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Common.internal_static_mymessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Common.internal_static_mymessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.Common.mymessage.class, protobuf.Common.mymessage.Builder.class);
      }

      // Construct using protobuf.Common.mymessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        myid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Common.internal_static_mymessage_descriptor;
      }

      public protobuf.Common.mymessage getDefaultInstanceForType() {
        return protobuf.Common.mymessage.getDefaultInstance();
      }

      public protobuf.Common.mymessage build() {
        protobuf.Common.mymessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.Common.mymessage buildPartial() {
        protobuf.Common.mymessage result = new protobuf.Common.mymessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.myid_ = myid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Common.mymessage) {
          return mergeFrom((protobuf.Common.mymessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.Common.mymessage other) {
        if (other == protobuf.Common.mymessage.getDefaultInstance()) return this;
        if (other.hasMyid()) {
          setMyid(other.getMyid());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.Common.mymessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.Common.mymessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 myid = 1;
      private int myid_ ;
      /**
       * <code>optional uint32 myid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public boolean hasMyid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 myid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public int getMyid() {
        return myid_;
      }
      /**
       * <code>optional uint32 myid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public Builder setMyid(int value) {
        bitField0_ |= 0x00000001;
        myid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 myid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public Builder clearMyid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        myid_ = 0;
        onChanged();
        return this;
      }

      // optional string message = 2;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       *
       * <pre>
       *发送的信息
       * </pre>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mymessage)
    }

    static {
      defaultInstance = new mymessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mymessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_msgcharinfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msgcharinfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mymessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mymessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\"\326\003\n\013msgcharinfo\022\014\n\004uaid\030\001" +
      " \001(\r\022\016\n\006charid\030\002 \001(\r\022\014\n\004kind\030\003 \001(\r\022\014\n\004na" +
      "me\030\004 \001(\t\022\014\n\004head\030\005 \001(\t\022\r\n\005level\030\006 \001(\r\022\013\n" +
      "\003exp\030\007 \001(\r\022\020\n\010phypower\030\010 \001(\r\022\022\n\nleadersh" +
      "ip\030\t \001(\r\022\021\n\tfriendnum\030\n \001(\r\022\020\n\010gamecoin\030" +
      "\013 \001(\r\022\017\n\007diamond\030\014 \001(\r\022\026\n\016friendshipoint" +
      "\030\r \001(\r\022\022\n\nreservecur\030\016 \001(\r\022\023\n\013nativepoin" +
      "t\030\017 \001(\r\022\023\n\013summonupper\030\020 \001(\r\022\030\n\020summonup" +
      "perlimit\030\021 \001(\r\022\022\n\ncreatetime\030\022 \001(\t\022\017\n\007gu" +
      "ildid\030\023 \001(\r\022\017\n\007victory\030\024 \001(\r\022\014\n\004fail\030\025 \001",
      "(\r\022\024\n\014max_gamecoin\030\026 \001(\r\022\023\n\013max_diamond\030" +
      "\027 \001(\r\022\025\n\rprotectedtime\030\030 \001(\r\022\021\n\ttotalcos" +
      "t\030\031 \001(\r\"*\n\tmymessage\022\014\n\004myid\030\001 \001(\r\022\017\n\007me" +
      "ssage\030\002 \001(\tB\n\n\010protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_msgcharinfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_msgcharinfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_msgcharinfo_descriptor,
              new java.lang.String[] { "Uaid", "Charid", "Kind", "Name", "Head", "Level", "Exp", "Phypower", "Leadership", "Friendnum", "Gamecoin", "Diamond", "Friendshipoint", "Reservecur", "Nativepoint", "Summonupper", "Summonupperlimit", "Createtime", "Guildid", "Victory", "Fail", "MaxGamecoin", "MaxDiamond", "Protectedtime", "Totalcost", });
          internal_static_mymessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mymessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mymessage_descriptor,
              new java.lang.String[] { "Myid", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
